[versions]

# Plugins
agp = "7.4.2"
kotlin = "1.9.24"

# AndroidX
activity = "1.8.2"
appcompat = "1.6.1"
core-ktx = "1.10.1"
constraint-layout = "2.1.4"
datastore-preferences = "1.0.0"

# KotlinX
kotlinx-coroutines-core = "1.7.3"

# Material
material = "1.9.0"

# Testing
espresso-core = "3.5.1"
androidx-junit = "1.1.5"
junit = "4.13.2"


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }


[libraries]

# AndroidX
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraint-layout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore-preferences" }

# KotlinX
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }

#Material
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Testing
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

[bundles]
androidx = [
    "androidx-activity",
    "androidx-appcompat",
    "androidx-constraintlayout",
    "androidx-core-ktx",
    "androidx-datastore-preferences",
]
